name: Build npm release

variables:
  esy__ci_cache_version: v1    # this is available to all jobs in env as $ESY__CI_CACHE_VERSION or in azure config as $(esy__ci_cache_version)

trigger:
  - master
  - global
  - release-*
  - releases-*
  - feature-*

jobs:
  - template: .ci/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04

  - template: .ci/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.14

  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - template: .ci/build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-10.14
      demands: node.js
    steps:
      - template: .ci/cross-release.yml
